In [1]:
import pandas as pd
import numpy as np
import allel
import os

In [2]:
strain=['A_J','AKR_J','BALB_CJ','CBA_J','C3H_HeJ','DBA_2J','LP_J']

tools=['BioGraph*',
'breakdancer',
'clever',
'delly',
'gasv',
'gridss',
'indelminer',
'lumpexpress',
'mistrvar',
'pindel',
'popdel',
'rdxplorer',
'smoove',
'sniffles',
'crest',
'genomestrip',
'manta_diploidSV']

In [3]:
df_10=pd.read_csv('../Data/analysis_files/df_10.csv')
df_100=pd.read_csv('../Data/analysis_files/df_100.csv')
df_1000=pd.read_csv('../Data/analysis_files/df_1000.csv')
df_10000=pd.read_csv('../Data/analysis_files/df_10000.csv')

df_10_nondel=pd.read_csv('../Data/analysis_files/df_10_nondel.csv')
df_100_nondel=pd.read_csv('../Data/analysis_files/df_100_nondel.csv')
df_1000_nondel=pd.read_csv('../Data/analysis_files/df_1000_nondel.csv')
df_10000_nondel=pd.read_csv('../Data/analysis_files/df_10000_nondel.csv')

pdList = [df_10,df_100,df_1000,df_10000,df_10_nondel,df_100_nondel,df_1000_nondel,df_10000_nondel] 
df_cat = pd.concat(pdList)

gs_=pd.read_csv('../Data/gold_standard/gs_')

In [4]:
df_cat.head()
df_cat = df_cat[df_cat['length'] >= 50]

In [5]:
df_cat.loc[(df_cat['length'] >= 50) & (df_cat['length'] < 100),'len'] = '50-100'
df_cat.loc[(df_cat['length'] >= 100) & (df_cat['length'] < 500),'len'] = '100-500'
df_cat.loc[(df_cat['length'] >= 500) & (df_cat['length'] < 1000),'len'] = '500-1000'
df_cat.loc[(df_cat['length'] >= 1000),'len'] = '1000+'
df_cat

,Unnamed: 0,flag,length,position,strain,threshold,tool,len
0,0,FP,228,3235828,LP_J,10,manta_diploidSV,100-500
1,1,FP,288,3236916,LP_J,10,manta_diploidSV,100-500
2,2,FP,93,6054981,LP_J,10,manta_diploidSV,50-100
3,3,FP,1728,6055200,LP_J,10,manta_diploidSV,1000+
4,4,FP,579,6057079,LP_J,10,manta_diploidSV,500-1000
5,5,FP,1914,7215483,LP_J,10,manta_diploidSV,1000+
6,6,FP,159,8888963,LP_J,10,manta_diploidSV,100-500
7,7,FP,1042,8889340,LP_J,10,manta_diploidSV,1000+
8,8,FP,310,8890098,LP_J,10,manta_diploidSV,100-500
9,9,FP,2647,17017839,LP_J,10,manta_diploidSV,1000+
10,10,FP,502,17075024,LP_J,10,manta_diploidSV,500-1000
11,11,FP,514,17075036,LP_J,10,manta_diploidSV,500-1000
12,12,FP,220,17076322,LP_J,10,manta_diploidSV,100-500
13,13,FP,34582733,17098517,LP_J,10,manta_diploidSV,1000+
14,14,FP,34583237,17098526,LP_J,10,manta_diploidSV,1000+
15,15,FP,153,17139160,LP_J,10,manta_diploidSV,100-500
16,16,FP,903,17173724,LP_J,10,manta_diploidSV,500-1000
17,17,FP,58,17229290,LP_J,10,manta_diploidSV,50-100
18,18,FP,116,17231864,LP_J,10,manta_diploidSV,100-500
19,19,FP,61,17245549,LP_J,10,manta_diploidSV,50-100
20,20,FP,200,17246880,LP_J,10,manta_diploidSV,100-500
21,21,FP,188,17258119,LP_J,10,manta_diploidSV,100-500
22,22,FP,971,17261023,LP_J,10,manta_diploidSV,500-1000
23,23,FP,60,17277244,LP_J,10,manta_diploidSV,50-100
24,24,FP,1242,17280368,LP_J,10,manta_diploidSV,1000+
25,25,FP,103,17286974,LP_J,10,manta_diploidSV,100-500
26,26,FP,950,17302161,LP_J,10,manta_diploidSV,500-1000
27,27,FP,7203,17302263,LP_J,10,manta_diploidSV,1000+
28,28,FP,6037,17303445,LP_J,10,manta_diploidSV,1000+
29,29,FP,107,17518874,LP_J,10,manta_diploidSV,100-500
...,...,...,...,...,...,...,...,...
109676,109676,TN,41353,60586059,A_J,10000,BioGraph*,1000+
109677,109677,TN,13663,60627593,A_J,10000,BioGraph*,1000+
109678,109678,TN,1415,60642338,A_J,10000,BioGraph*,1000+
109679,109679,TN,1415,60642338,A_J,10000,BioGraph*,1000+
109680,109680,TN,6850,60650231,A_J,10000,BioGraph*,1000+
109681,109681,TN,6850,60650231,A_J,10000,BioGraph*,1000+
109682,109682,TN,20417,60670325,A_J,10000,BioGraph*,1000+
109683,109683,TN,12805,60690838,A_J,10000,BioGraph*,1000+
109684,109684,TN,12805,60690838,A_J,10000,BioGraph*,1000+
109685,109685,TN,39435,60704776,A_J,10000,BioGraph*,1000+
109686,109686,TN,57200,60744337,A_J,10000,BioGraph*,1000+
109687,109687,TN,57200,60744337,A_J,10000,BioGraph*,1000+
109688,109688,TN,27132,60801683,A_J,10000,BioGraph*,1000+
109689,109689,TN,8746,60829507,A_J,10000,BioGraph*,1000+
109690,109690,TN,8746,60829507,A_J,10000,BioGraph*,1000+
109691,109691,TN,14678,60838313,A_J,10000,BioGraph*,1000+
109692,109692,TN,14678,60838313,A_J,10000,BioGraph*,1000+
109693,109693,TN,72177,60853125,A_J,10000,BioGraph*,1000+
109694,109694,TN,72177,60853125,A_J,10000,BioGraph*,1000+
109695,109695,TN,14570,60934033,A_J,10000,BioGraph*,1000+
109696,109696,TN,72695,60948759,A_J,10000,BioGraph*,1000+
109697,109697,TN,5152,61021508,A_J,10000,BioGraph*,1000+
109698,109698,TN,87325,61026863,A_J,10000,BioGraph*,1000+
109699,109699,TN,3843,61114797,A_J,10000,BioGraph*,1000+
109700,109700,TN,13515,61118709,A_J,10000,BioGraph*,1000+
109701,109701,TN,36477,61132293,A_J,10000,BioGraph*,1000+
109702,109702,TN,36477,61132293,A_J,10000,BioGraph*,1000+
109703,109703,TN,8527,61175238,A_J,10000,BioGraph*,1000+
109704,109704,TN,8206,61184017,A_J,10000,BioGraph*,1000+
109705,109705,TN,239222,61192344,A_J,10000,BioGraph*,1000+

In [6]:
df_merge_all_len=pd.merge(df_cat, gs_,on=['strain','len'])
del df_merge_all_len['Unnamed: 0_x']
del df_merge_all_len['Unnamed: 0_y']
df_merge_all_len

,flag,length,position,strain,threshold,tool,len,n_true
0,FP,228,3235828,LP_J,10,manta_diploidSV,100-500,228
1,FP,288,3236916,LP_J,10,manta_diploidSV,100-500,228
2,FP,159,8888963,LP_J,10,manta_diploidSV,100-500,228
3,FP,310,8890098,LP_J,10,manta_diploidSV,100-500,228
4,FP,220,17076322,LP_J,10,manta_diploidSV,100-500,228
5,FP,153,17139160,LP_J,10,manta_diploidSV,100-500,228
6,FP,116,17231864,LP_J,10,manta_diploidSV,100-500,228
7,FP,200,17246880,LP_J,10,manta_diploidSV,100-500,228
8,FP,188,17258119,LP_J,10,manta_diploidSV,100-500,228
9,FP,103,17286974,LP_J,10,manta_diploidSV,100-500,228
10,FP,107,17518874,LP_J,10,manta_diploidSV,100-500,228
11,FP,118,17716071,LP_J,10,manta_diploidSV,100-500,228
12,FP,313,18121683,LP_J,10,manta_diploidSV,100-500,228
13,FP,117,18863615,LP_J,10,manta_diploidSV,100-500,228
14,FP,129,18899002,LP_J,10,manta_diploidSV,100-500,228
15,FP,346,18926461,LP_J,10,manta_diploidSV,100-500,228
16,FP,395,19795589,LP_J,10,manta_diploidSV,100-500,228
17,FP,401,19916412,LP_J,10,manta_diploidSV,100-500,228
18,FP,128,20391048,LP_J,10,manta_diploidSV,100-500,228
19,FP,121,21474373,LP_J,10,manta_diploidSV,100-500,228
20,FP,241,21515316,LP_J,10,manta_diploidSV,100-500,228
21,FP,420,21598332,LP_J,10,manta_diploidSV,100-500,228
22,FP,108,21839215,LP_J,10,manta_diploidSV,100-500,228
23,FP,244,21881595,LP_J,10,manta_diploidSV,100-500,228
24,FP,399,21911440,LP_J,10,manta_diploidSV,100-500,228
25,FP,282,21919888,LP_J,10,manta_diploidSV,100-500,228
26,FP,209,22253968,LP_J,10,manta_diploidSV,100-500,228
27,FP,164,22797444,LP_J,10,manta_diploidSV,100-500,228
28,FP,366,23059337,LP_J,10,manta_diploidSV,100-500,228
29,FP,195,23213868,LP_J,10,manta_diploidSV,100-500,228
...,...,...,...,...,...,...,...,...
1092204,TN,971,46752618,A_J,10000,clever,500-1000,74
1092205,TN,802,47158123,A_J,10000,clever,500-1000,74
1092206,TN,802,47158123,A_J,10000,clever,500-1000,74
1092207,TN,802,47158123,A_J,10000,clever,500-1000,74
1092208,TN,958,47694261,A_J,10000,clever,500-1000,74
1092209,TN,797,47973408,A_J,10000,clever,500-1000,74
1092210,TN,909,48053685,A_J,10000,clever,500-1000,74
1092211,TN,909,48053685,A_J,10000,clever,500-1000,74
1092212,TN,928,50907692,A_J,10000,clever,500-1000,74
1092213,TN,803,52759592,A_J,10000,clever,500-1000,74
1092214,TN,952,53588126,A_J,10000,clever,500-1000,74
1092215,TN,757,58318422,A_J,10000,clever,500-1000,74
1092216,TN,792,58966692,A_J,10000,clever,500-1000,74
1092217,TN,788,59213074,A_J,10000,clever,500-1000,74
1092218,TN,877,60056150,A_J,10000,clever,500-1000,74
1092219,TN,732,60828785,A_J,10000,clever,500-1000,74
1092220,TN,732,60828785,A_J,10000,clever,500-1000,74
1092221,TN,732,60828785,A_J,10000,clever,500-1000,74
1092222,TN,734,61114149,A_J,10000,clever,500-1000,74
1092223,TN,734,61114149,A_J,10000,clever,500-1000,74
1092224,TN,946,10806737,A_J,10000,breakdancer,500-1000,74
1092225,TN,577,38021221,A_J,10000,breakdancer,500-1000,74
1092226,TN,577,38021221,A_J,10000,breakdancer,500-1000,74
1092227,TN,577,38021221,A_J,10000,breakdancer,500-1000,74
1092228,TN,919,39516782,A_J,10000,breakdancer,500-1000,74
1092229,TN,724,59953001,A_J,10000,breakdancer,500-1000,74
1092230,TN,919,61025771,A_J,10000,breakdancer,500-1000,74
1092231,TN,852,61113384,A_J,10000,breakdancer,500-1000,74
1092232,TN,901,39516781,A_J,10000,BioGraph*,500-1000,74
1092233,TN,530,59952237,A_J,10000,BioGraph*,500-1000,74

In [7]:
df_count_TP = df_merge_all_len[df_merge_all_len['flag'] == 'TP'].groupby(['tool','threshold','strain','len','n_true'],as_index=False)['flag'].count()
df_count_TP = df_count_TP.rename(columns={"flag": "nTP"})
df_count_TP.shape
df_count_TP.head()

        tool  threshold strain       len  n_true  nTP
0  BioGraph*         10  AKR_J   100-500     234   19
1  BioGraph*         10  AKR_J     1000+     140   10
2  BioGraph*         10  AKR_J    50-100      37    2
3  BioGraph*         10  AKR_J  500-1000      83    5
4  BioGraph*         10    A_J   100-500     249   29

In [8]:
df_count_FP = df_merge_all_len[df_merge_all_len['flag'] == 'FP'].groupby(['tool','threshold','strain','len','n_true'],as_index=False)['flag'].count()
df_count_FP = df_count_FP.rename(columns={"flag": "nFP"})
df_count_FP.shape
df_count_FP.head()

        tool  threshold strain       len  n_true  nFP
0  BioGraph*         10  AKR_J   100-500     234  153
1  BioGraph*         10  AKR_J     1000+     140   77
2  BioGraph*         10  AKR_J    50-100      37  132
3  BioGraph*         10  AKR_J  500-1000      83   27
4  BioGraph*         10    A_J   100-500     249  162

In [9]:
df_count_TN = df_merge_all_len[df_merge_all_len['flag'] == 'TN'].groupby(['tool','threshold','strain','len','n_true'],as_index=False)['flag'].count()
df_count_TN = df_count_TN.rename(columns={"flag": "nTN"})
df_count_TN.shape
df_count_TN.head()

        tool  threshold   strain       len  n_true  nTN
0  BioGraph*         10    AKR_J     1000+     140  205
1  BioGraph*         10    AKR_J  500-1000      83    1
2  BioGraph*         10      A_J     1000+     158  220
3  BioGraph*         10  BALB_CJ     1000+     157  235
4  BioGraph*         10  BALB_CJ  500-1000      77    2

In [10]:
#for s in strain:
    #for t in tools:
        #for th in [10,100,1000,10000]:
            #for l in ["50-100","100-500","500-1000","1000+"]:
                #if not (((df_count_TP['tool'] == t) & (df_count_TP['strain'] == s) & (df_count_TP['threshold'] == th) & (df_count_TP['len'] == l)).any()):
                    #df_count_TP = df_count_TP.append({'tool' : t , 'strain' : s, 'len' : l,'threshold' : th,'nTP' : 0} , ignore_index=True)
#df_count_TP.shape
#df_count_TP.head()

In [11]:
df_merged = pd.DataFrame(columns=['tool', 'threshold', 'strain', 'len','nTP', 'nFP','nTN'])

for s in strain:
    for t in tools:
        for th in [10,100,1000,10000]:
            for l in ["50-100","100-500","500-1000","1000+"]:
                #dfObj = dfObj.append({'User_ID': 25, 'UserName': 'Jack', 'Action': 'Login'}, ignore_index=True)
                if (((df_count_TP['tool'] == t) & (df_count_TP['strain'] == s) & (df_count_TP['threshold'] == th) & (df_count_TP['len'] == l)).any()):
                    tp = df_count_TP[(df_count_TP['tool'] == t) & (df_count_TP['strain'] == s) & (df_count_TP['threshold'] == th) & (df_count_TP['len'] == l)]
                    tp = tp['nTP']
                    tp = tp.values[0]
                else:
                    tp = 0
                    
                if (((df_count_FP['tool'] == t) & (df_count_FP['strain'] == s) & (df_count_FP['threshold'] == th) & (df_count_FP['len'] == l)).any()):
                    fp = df_count_FP[(df_count_FP['tool'] == t) & (df_count_FP['strain'] == s) & (df_count_FP['threshold'] == th) & (df_count_FP['len'] == l)]
                    fp = fp['nFP']
                    fp = fp.values[0]
                else:
                    fp = 0
                 
                if (((df_count_TN['tool'] == t) & (df_count_TN['strain'] == s) & (df_count_TN['threshold'] == th) & (df_count_TN['len'] == l)).any()):
                    tn = df_count_TN[(df_count_TN['tool'] == t) & (df_count_TN['strain'] == s) & (df_count_TN['threshold'] == th) & (df_count_TN['len'] == l)]
                    tn = tn['nTN']
                    tn = tn.values[0]
                else: 
                    tn = 0
                
                #print(tp.values[0])
                df_merged = df_merged.append({'tool':t, 'threshold':th, 'strain':s, 'len':l,'nTP':tp, 'nFP':fp,'nTN':tn},ignore_index=True)
#df_count_TP.shape

In [12]:
df_merged

                 tool threshold strain       len  nTP  nFP  nTN
0           BioGraph*        10    A_J    50-100    2  136    0
1           BioGraph*        10    A_J   100-500   29  162    0
2           BioGraph*        10    A_J  500-1000    3   29    0
3           BioGraph*        10    A_J     1000+   13   94  220
4           BioGraph*       100    A_J    50-100   19  119    0
5           BioGraph*       100    A_J   100-500  147   44    0
6           BioGraph*       100    A_J  500-1000   26    6    2
7           BioGraph*       100    A_J     1000+   87   20  315
8           BioGraph*      1000    A_J    50-100   27  111    0
9           BioGraph*      1000    A_J   100-500  158   33    0
10          BioGraph*      1000    A_J  500-1000   29    3    2
11          BioGraph*      1000    A_J     1000+   90   17  329
12          BioGraph*     10000    A_J    50-100   43   95    0
13          BioGraph*     10000    A_J   100-500  162   29    1
14          BioGraph*     10000    A_J  500-1000   28    4    2
15          BioGraph*     10000    A_J     1000+   90   17  382
16        breakdancer        10    A_J    50-100    0    0    0
17        breakdancer        10    A_J   100-500    9  398    0
18        breakdancer        10    A_J  500-1000    1   55    3
19        breakdancer        10    A_J     1000+    1  146  247
20        breakdancer       100    A_J    50-100    0    0    0
21        breakdancer       100    A_J   100-500  141  266    0
22        breakdancer       100    A_J  500-1000   41   15    4
23        breakdancer       100    A_J     1000+  103   44  313
24        breakdancer      1000    A_J    50-100    0    0    0
25        breakdancer      1000    A_J   100-500  194  213    1
26        breakdancer      1000    A_J  500-1000   48    8    5
27        breakdancer      1000    A_J     1000+  118   29  356
28        breakdancer     10000    A_J    50-100    0    0    0
29        breakdancer     10000    A_J   100-500  206  201    1
...               ...       ...    ...       ...  ...  ...  ...
1874      genomestrip        10   LP_J  500-1000    3   37   18
1875      genomestrip        10   LP_J     1000+   11  149   98
1876      genomestrip       100   LP_J    50-100    0    0    0
1877      genomestrip       100   LP_J   100-500    0    0    0
1878      genomestrip       100   LP_J  500-1000   25   15   27
1879      genomestrip       100   LP_J     1000+   98   62  144
1880      genomestrip      1000   LP_J    50-100    0    0    0
1881      genomestrip      1000   LP_J   100-500    0    0    0
1882      genomestrip      1000   LP_J  500-1000   34    6   35
1883      genomestrip      1000   LP_J     1000+  110   50  154
1884      genomestrip     10000   LP_J    50-100    0    0    0
1885      genomestrip     10000   LP_J   100-500    0    0    0
1886      genomestrip     10000   LP_J  500-1000   37    3   61
1887      genomestrip     10000   LP_J     1000+  113   47  201
1888  manta_diploidSV        10   LP_J    50-100    5  120   12
1889  manta_diploidSV        10   LP_J   100-500   31  159   69
1890  manta_diploidSV        10   LP_J  500-1000    7   37   20
1891  manta_diploidSV        10   LP_J     1000+   17  106  772
1892  manta_diploidSV       100   LP_J    50-100   26   99   27
1893  manta_diploidSV       100   LP_J   100-500  156   34  157
1894  manta_diploidSV       100   LP_J  500-1000   36    8   38
1895  manta_diploidSV       100   LP_J     1000+   94   29  830
1896  manta_diploidSV      1000   LP_J    50-100   29   96   32
1897  manta_diploidSV      1000   LP_J   100-500  164   26  167
1898  manta_diploidSV      1000   LP_J  500-1000   38    6   40
1899  manta_diploidSV      1000   LP_J     1000+  106   17  838
1900  manta_diploidSV     10000   LP_J    50-100   49   76   95
1901  manta_diploidSV     10000   LP_J   100-500  169   21  261
1902  manta_diploidSV     10000   LP_J  500-1000   39    5   69
1903  manta_diploidSV     10000   LP_J     1000+  104   19  868

[1904 rows x 7 columns]

In [20]:
df_merged["threshold"] = pd.to_numeric(df_merged["threshold"])

In [21]:
df_merge_all_len.dtypes

flag         object
length        int64
position      int64
strain       object
threshold     int64
tool         object
len          object
n_true        int64
dtype: object

In [22]:
df_merged_all=pd.merge(df_merged, df_merge_all_len,on=['strain','len','tool','threshold'])
del df_merged_all['length']
del df_merged_all['flag']
del df_merged_all['position']
df_merged_all

                    tool  threshold strain     len  nTP  nFP  nTN  n_true
0              BioGraph*         10    A_J  50-100    2  136    0      37
1              BioGraph*         10    A_J  50-100    2  136    0      37
2              BioGraph*         10    A_J  50-100    2  136    0      37
3              BioGraph*         10    A_J  50-100    2  136    0      37
4              BioGraph*         10    A_J  50-100    2  136    0      37
5              BioGraph*         10    A_J  50-100    2  136    0      37
6              BioGraph*         10    A_J  50-100    2  136    0      37
7              BioGraph*         10    A_J  50-100    2  136    0      37
8              BioGraph*         10    A_J  50-100    2  136    0      37
9              BioGraph*         10    A_J  50-100    2  136    0      37
10             BioGraph*         10    A_J  50-100    2  136    0      37
11             BioGraph*         10    A_J  50-100    2  136    0      37
12             BioGraph*         10    A_J  50-100    2  136    0      37
13             BioGraph*         10    A_J  50-100    2  136    0      37
14             BioGraph*         10    A_J  50-100    2  136    0      37
15             BioGraph*         10    A_J  50-100    2  136    0      37
16             BioGraph*         10    A_J  50-100    2  136    0      37
17             BioGraph*         10    A_J  50-100    2  136    0      37
18             BioGraph*         10    A_J  50-100    2  136    0      37
19             BioGraph*         10    A_J  50-100    2  136    0      37
20             BioGraph*         10    A_J  50-100    2  136    0      37
21             BioGraph*         10    A_J  50-100    2  136    0      37
22             BioGraph*         10    A_J  50-100    2  136    0      37
23             BioGraph*         10    A_J  50-100    2  136    0      37
24             BioGraph*         10    A_J  50-100    2  136    0      37
25             BioGraph*         10    A_J  50-100    2  136    0      37
26             BioGraph*         10    A_J  50-100    2  136    0      37
27             BioGraph*         10    A_J  50-100    2  136    0      37
28             BioGraph*         10    A_J  50-100    2  136    0      37
29             BioGraph*         10    A_J  50-100    2  136    0      37
...                  ...        ...    ...     ...  ...  ...  ...     ...
1092204  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092205  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092206  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092207  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092208  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092209  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092210  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092211  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092212  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092213  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092214  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092215  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092216  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092217  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092218  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092219  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092220  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092221  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092222  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092223  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092224  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092225  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092226  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092227  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092228  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092229  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092230  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092231  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092232  manta_diploidSV      10000   LP_J   1000+  104   19  868     139
1092233  manta_diploidSV      10000   LP_J   1000+  104   19  868     139

[1092234 rows x 8 columns]

In [23]:
df_merged_all['nFN']=df_merged_all['n_true']-df_merged_all['nTP']
df_merged_all

                    tool  threshold strain     len  nTP  nFP  nTN  n_true nFN
0              BioGraph*         10    A_J  50-100    2  136    0      37  35
1              BioGraph*         10    A_J  50-100    2  136    0      37  35
2              BioGraph*         10    A_J  50-100    2  136    0      37  35
3              BioGraph*         10    A_J  50-100    2  136    0      37  35
4              BioGraph*         10    A_J  50-100    2  136    0      37  35
5              BioGraph*         10    A_J  50-100    2  136    0      37  35
6              BioGraph*         10    A_J  50-100    2  136    0      37  35
7              BioGraph*         10    A_J  50-100    2  136    0      37  35
8              BioGraph*         10    A_J  50-100    2  136    0      37  35
9              BioGraph*         10    A_J  50-100    2  136    0      37  35
10             BioGraph*         10    A_J  50-100    2  136    0      37  35
11             BioGraph*         10    A_J  50-100    2  136    0      37  35
12             BioGraph*         10    A_J  50-100    2  136    0      37  35
13             BioGraph*         10    A_J  50-100    2  136    0      37  35
14             BioGraph*         10    A_J  50-100    2  136    0      37  35
15             BioGraph*         10    A_J  50-100    2  136    0      37  35
16             BioGraph*         10    A_J  50-100    2  136    0      37  35
17             BioGraph*         10    A_J  50-100    2  136    0      37  35
18             BioGraph*         10    A_J  50-100    2  136    0      37  35
19             BioGraph*         10    A_J  50-100    2  136    0      37  35
20             BioGraph*         10    A_J  50-100    2  136    0      37  35
21             BioGraph*         10    A_J  50-100    2  136    0      37  35
22             BioGraph*         10    A_J  50-100    2  136    0      37  35
23             BioGraph*         10    A_J  50-100    2  136    0      37  35
24             BioGraph*         10    A_J  50-100    2  136    0      37  35
25             BioGraph*         10    A_J  50-100    2  136    0      37  35
26             BioGraph*         10    A_J  50-100    2  136    0      37  35
27             BioGraph*         10    A_J  50-100    2  136    0      37  35
28             BioGraph*         10    A_J  50-100    2  136    0      37  35
29             BioGraph*         10    A_J  50-100    2  136    0      37  35
...                  ...        ...    ...     ...  ...  ...  ...     ...  ..
1092204  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092205  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092206  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092207  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092208  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092209  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092210  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092211  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092212  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092213  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092214  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092215  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092216  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092217  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092218  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092219  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092220  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092221  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092222  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092223  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092224  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092225  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092226  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092227  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092228  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092229  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092230  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092231  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092232  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35
1092233  manta_diploidSV      10000   LP_J   1000+  104   19  868     139  35

[1092234 rows x 9 columns]

In [24]:
df_merged_all = df_merged_all.astype({'nTP': 'float64', 'nFP': 'float64', 'nTN': 'float64', 'nFN': 'float64'})

df_merged_all['sensitivity']=df_merged_all['nTP']/df_merged_all['n_true']
df_merged_all['precision']=df_merged_all['nTP']/(df_merged_all['nTP'] + df_merged_all['nFP'])                                                                                    
df_merged_all['specificity']=df_merged_all['nTN']/(df_merged_all['nTN']+df_merged_all['nFP'])
df_merged_all['f-score']=2*(df_merged_all['sensitivity']*df_merged_all['precision'])/(df_merged_all['sensitivity']+df_merged_all['precision']+0.00000001)

df_merged_all = df_merged_all.astype({'nTP':'int64', 'nFP':'int64', 'nTN':'int64'})
df_merged_all.loc[np.isnan(df_merged_all['precision']), 'precision'] = 0

df_merged_all.tail()

,tool,threshold,strain,len,nTP,nFP,nTN,n_true,nFN,sensitivity,precision,specificity,f-score
1092229,manta_diploidSV,10000,LP_J,1000+,104,19,868,139,35.0,0.748201,0.845528,0.978579,0.793893
1092230,manta_diploidSV,10000,LP_J,1000+,104,19,868,139,35.0,0.748201,0.845528,0.978579,0.793893
1092231,manta_diploidSV,10000,LP_J,1000+,104,19,868,139,35.0,0.748201,0.845528,0.978579,0.793893
1092232,manta_diploidSV,10000,LP_J,1000+,104,19,868,139,35.0,0.748201,0.845528,0.978579,0.793893
1092233,manta_diploidSV,10000,LP_J,1000+,104,19,868,139,35.0,0.748201,0.845528,0.978579,0.793893

In [ ]:
df_merged_all.to_csv('../Data/analysis_files/df_merged_all.csv')