# Concatenating all tools and strains at threshold 0, 10, 100, 1000, and 10K

In [14]:
import os
import allel
import pandas as pd


strain=['A_J','AKR_J','BALB_CJ','CBA_J','C3H_HeJ','DBA_2J','LP_J']

tools=['BioGraph*',
'breakdancer',
'clever',
'delly',
'gasv',
'gridss',
'indelminer',
'lumpexpress',
'mistrvar',
'pindel',
'popdel',
'rdxplorer',
'smoove',
'sniffles',
'crest',
'genomestrip',
'manta_diploidSV']

## 0 bp Threshold

In [15]:
#0 threshold deletions

th=0
df_current = pd.DataFrame(columns=['strain','length','flag','position','threshold'])
df_0 = pd.DataFrame(columns=['tool','strain','length','flag','position','threshold'])
for s in strain:
    for t in tools:
        file='../Data/raw_data/mouse/custom_vcf_fulldata/'+str(th)+'t/deletions/nf_'+str(th)+'t.'+t+'.'+s+'.chr19.100p_sorted.modified.vcf'
        
        callset = allel.read_vcf(file,fields='*')
        if callset!=None:
            df_current = pd.DataFrame({'tool': t, 'strain': s, 'length': callset['variants/SVLEN'],'flag': callset['variants/FLAG'],'position': callset['variants/POS'],'threshold': th})
            df_0 = pd.concat([df_current, df_0],ignore_index=True)   
        
        else:
            print("Empty File: " + file)
            
df_0.head()

/home/vs/.local/lib/python3.5/site-packages/ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  del sys.path[0]

  flag length position strain threshold             tool
0   FP    228  3235828   LP_J         0  manta_diploidSV
1   FP    288  3236916   LP_J         0  manta_diploidSV
2   FP     93  6054981   LP_J         0  manta_diploidSV
3   FP   1728  6055200   LP_J         0  manta_diploidSV
4   FP    579  6057079   LP_J         0  manta_diploidSV

In [16]:
#0 threshold non-deletions
import os

th=0
df_current = pd.DataFrame(columns=['strain','length','flag','position','threshold'])
df_0_nondel = pd.DataFrame(columns=['tool','strain','length','flag','position','threshold'])
for s in strain:
    for t in tools:
        
        file='../Data/raw_data/mouse/custom_vcf_fulldata/'+str(th)+'t/non-deletions/nf_'+str(th)+'t.'+t+'.'+s+'.chr19.100p_sorted.modified.nondel.vcf'
        
        callset = allel.read_vcf(file,fields='*')
        if callset!=None:
            print ("----")
            df_current = pd.DataFrame({'tool': t, 'strain': s, 'length': callset['variants/SVLEN'],'flag': callset['variants/FLAG'],'position': callset['variants/POS'],'threshold': th})
            df_0_nondel = pd.concat([df_current, df_0_nondel],ignore_index=True)   
            
        else:
            print("Empty File: " + file)
        
df_0_nondel.head()

----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----

/home/vs/.local/lib/python3.5/site-packages/ipykernel_launcher.py:16: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  app.launch_new_instance()

----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----
----

  flag length  position strain threshold             tool
0          -1         0   LP_J         0  manta_diploidSV
1          -1         0   LP_J         0  manta_diploidSV
2   TN     84  17072680   LP_J         0  manta_diploidSV
3   TN    502  17075024   LP_J         0  manta_diploidSV
4   TN    514  17075036   LP_J         0  manta_diploidSV

## 10 bp Threshold

In [17]:
#10 threshold deletions
#missing files: pindel.BALB_CJ, and platypus.BALB_CJ
#tools were not able to run on mouse data; ignore?

th=10     
df_current = pd.DataFrame(columns=['strain','length','flag','position','threshold'])
df_10 = pd.DataFrame(columns=['tool','strain','length','flag','position','threshold'])

for s in strain:
    for t in tools:
        file='../Data/raw_data/mouse/custom_vcf_fulldata/'+str(th)+'t/deletions/nf_'+str(th)+'t.'+t+'.'+s+'.chr19.100p_sorted.modified.vcf'
        
        if os.path.exists(file):
            callset = allel.read_vcf(file,fields='*')
            if callset!=None:
                df_current = pd.DataFrame({'tool': t, 'strain': s, 'length': callset['variants/SVLEN'],'flag': callset['variants/FLAG'],'position': callset['variants/POS'],'threshold': th})
                df_10 = pd.concat([df_current, df_10],ignore_index=True)

            else:
                print("Empty File: " + file)
        else:
            print("Nonexistant File: " + file)
            
df_10.head()

/home/vs/.local/lib/python3.5/site-packages/ipykernel_launcher.py:17: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  flag length position strain threshold             tool
0   FP    228  3235828   LP_J        10  manta_diploidSV
1   FP    288  3236916   LP_J        10  manta_diploidSV
2   FP     93  6054981   LP_J        10  manta_diploidSV
3   FP   1728  6055200   LP_J        10  manta_diploidSV
4   FP    579  6057079   LP_J        10  manta_diploidSV

In [18]:
#10 threshold non-deletions
th=10     
df_current = pd.DataFrame(columns=['strain','length','flag','position','threshold'])
df_10_nondel = pd.DataFrame(columns=['tool','strain','length','flag','position','threshold'])

for s in strain:
    for t in tools:
        file='../Data/raw_data/mouse/custom_vcf_fulldata/'+str(th)+'t/non-deletions/nf_'+str(th)+'t.'+t+'.'+s+'.chr19.100p_sorted.modified.nondel.vcf'
        
        callset = allel.read_vcf(file,fields='*')
        if callset!=None:
            df_current = pd.DataFrame({'tool': t, 'strain': s, 'length': callset['variants/SVLEN'],'flag': callset['variants/FLAG'],'position': callset['variants/POS'],'threshold': th})
            df_10_nondel = pd.concat([df_current, df_10_nondel],ignore_index=True)
            
        else:
            print("Empty File: " + file)
            
df_10_nondel.head()

/home/vs/.local/lib/python3.5/site-packages/ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  del sys.path[0]

  flag length  position strain threshold             tool
0          -1         0   LP_J        10  manta_diploidSV
1          -1         0   LP_J        10  manta_diploidSV
2   TN    215  16852931   LP_J        10  manta_diploidSV
3   TN     84  17072680   LP_J        10  manta_diploidSV
4   TN    502  17075024   LP_J        10  manta_diploidSV

## 100 bp Threshold

In [19]:
#100 threshold deletions
#missing files: pindel.BALB_CJ, and platypus.BALB_CJ

th=100
df_current = pd.DataFrame(columns=['strain','length','flag','position','threshold'])
df_100 = pd.DataFrame(columns=['tool','strain','length','flag','position','threshold'])

for s in strain:
    for t in tools:
        file='../Data/raw_data/mouse/custom_vcf_fulldata/'+str(th)+'t/deletions/nf_'+str(th)+'t.'+t+'.'+s+'.chr19.100p_sorted.modified.vcf'
        
        if os.path.exists(file):
            callset = allel.read_vcf(file,fields='*')
            if callset!=None:
                df_current = pd.DataFrame({'tool': t, 'strain': s, 'length': callset['variants/SVLEN'],'flag': callset['variants/FLAG'],'position': callset['variants/POS'],'threshold': th})
                df_100 = pd.concat([df_current, df_100],ignore_index=True)
        
            else:
                print("Empty File: " + file)
                
        else:
            print("Nonexistant File: " + file)
            
df_100.head()

/home/vs/.local/lib/python3.5/site-packages/ipykernel_launcher.py:16: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  app.launch_new_instance()

  flag length position strain threshold             tool
0   FP    228  3235828   LP_J       100  manta_diploidSV
1   FP    288  3236916   LP_J       100  manta_diploidSV
2   FP     93  6054981   LP_J       100  manta_diploidSV
3   FP   1728  6055200   LP_J       100  manta_diploidSV
4   FP    579  6057079   LP_J       100  manta_diploidSV

In [20]:
#100 threshold non-deletions

th=100     
df_current = pd.DataFrame(columns=['strain','length','flag','position','threshold'])
df_100_nondel = pd.DataFrame(columns=['tool','strain','length','flag','position','threshold'])

for s in strain:
    for t in tools:
        file='../Data/raw_data/mouse/custom_vcf_fulldata/'+str(th)+'t/non-deletions/nf_'+str(th)+'t.'+t+'.'+s+'.chr19.100p_sorted.modified.nondel.vcf'
        callset = allel.read_vcf(file,fields='*')
        if callset!=None:
            df_current = pd.DataFrame({'tool': t, 'strain': s, 'length': callset['variants/SVLEN'],'flag': callset['variants/FLAG'],'position': callset['variants/POS'],'threshold': th})
            df_100_nondel = pd.concat([df_current, df_100_nondel],ignore_index=True)
            
        else:
            print("Empty File: " + file)
            
df_100_nondel.head()

/home/vs/.local/lib/python3.5/site-packages/ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  del sys.path[0]

  flag length  position strain threshold             tool
0          -1         0   LP_J       100  manta_diploidSV
1          -1         0   LP_J       100  manta_diploidSV
2   TN    215  16852931   LP_J       100  manta_diploidSV
3   TN   2647  17017839   LP_J       100  manta_diploidSV
4   TN     84  17072680   LP_J       100  manta_diploidSV

## 1000 bp Threshold

In [21]:
#1000 threshold deletions
#missing files: pindel.BALB_CJ, and platypus.BALB_CJ

th=1000    
df_current = pd.DataFrame(columns=['strain','length','flag','position','threshold'])
df_1000 = pd.DataFrame(columns=['tool','strain','length','flag','position','threshold'])

for s in strain:
    for t in tools:
        file='../Data/raw_data/mouse/custom_vcf_fulldata/'+str(th)+'t/deletions/nf_'+str(th)+'t.'+t+'.'+s+'.chr19.100p_sorted.modified.vcf'
        
        if os.path.exists(file):
            callset = allel.read_vcf(file,fields='*')
            if callset!=None:
                df_current = pd.DataFrame({'tool': t, 'strain': s, 'length': callset['variants/SVLEN'],'flag': callset['variants/FLAG'],'position': callset['variants/POS'],'threshold': th})
                df_1000 = pd.concat([df_current, df_1000],ignore_index=True)
            
        else:
            print("Empty File: " + file)
            
    else:
        print ("Nonexistant File: " + file)
           
df_1000.head()

/home/vs/.local/lib/python3.5/site-packages/ipykernel_launcher.py:16: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  app.launch_new_instance()

Nonexistant File: ../Data/raw_data/mouse/custom_vcf_fulldata/1000t/deletions/nf_1000t.manta_diploidSV.A_J.chr19.100p_sorted.modified.vcf
Nonexistant File: ../Data/raw_data/mouse/custom_vcf_fulldata/1000t/deletions/nf_1000t.manta_diploidSV.AKR_J.chr19.100p_sorted.modified.vcf
Nonexistant File: ../Data/raw_data/mouse/custom_vcf_fulldata/1000t/deletions/nf_1000t.manta_diploidSV.BALB_CJ.chr19.100p_sorted.modified.vcf
Nonexistant File: ../Data/raw_data/mouse/custom_vcf_fulldata/1000t/deletions/nf_1000t.manta_diploidSV.CBA_J.chr19.100p_sorted.modified.vcf
Nonexistant File: ../Data/raw_data/mouse/custom_vcf_fulldata/1000t/deletions/nf_1000t.manta_diploidSV.C3H_HeJ.chr19.100p_sorted.modified.vcf
Nonexistant File: ../Data/raw_data/mouse/custom_vcf_fulldata/1000t/deletions/nf_1000t.manta_diploidSV.DBA_2J.chr19.100p_sorted.modified.vcf
Nonexistant File: ../Data/raw_data/mouse/custom_vcf_fulldata/1000t/deletions/nf_1000t.manta_diploidSV.LP_J.chr19.100p_sorted.modified.vcf

  flag length position strain threshold             tool
0   FP    228  3235828   LP_J      1000  manta_diploidSV
1   FP    288  3236916   LP_J      1000  manta_diploidSV
2   FP     93  6054981   LP_J      1000  manta_diploidSV
3   FP    579  6057079   LP_J      1000  manta_diploidSV
4   FP   1914  7215483   LP_J      1000  manta_diploidSV

In [22]:
#1000 threshold non-deletions

th=1000    
df_current = pd.DataFrame(columns=['strain','length','flag','position','threshold'])
df_1000_nondel = pd.DataFrame(columns=['tool','strain','length','flag','position','threshold'])

for s in strain:
    for t in tools:
        file='../Data/raw_data/mouse/custom_vcf_fulldata/'+str(th)+'t/non-deletions/nf_'+str(th)+'t.'+t+'.'+s+'.chr19.100p_sorted.modified.nondel.vcf'
        
        
        callset = allel.read_vcf(file,fields='*')
        if callset!=None:
            df_current = pd.DataFrame({'tool': t, 'strain': s, 'length': callset['variants/SVLEN'],'flag': callset['variants/FLAG'],'position': callset['variants/POS'],'threshold': th})
            df_1000_nondel = pd.concat([df_current, df_1000_nondel],ignore_index=True)
            
        else:
            print("Empty File: " + file)
        
df_1000_nondel.head()

/home/vs/.local/lib/python3.5/site-packages/ipykernel_launcher.py:15: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  from ipykernel import kernelapp as app

  flag length position strain threshold             tool
0          -1        0   LP_J      1000  manta_diploidSV
1          -1        0   LP_J      1000  manta_diploidSV
2   TN   1728  6055200   LP_J      1000  manta_diploidSV
3   TN   1042  8889340   LP_J      1000  manta_diploidSV
4   TN    310  8890098   LP_J      1000  manta_diploidSV

## 10000 bp Threshold

In [23]:
#10000 threshold deletions
#missing files: pindel.BALB_CJ, and platypus.BALB_CJ

th=10000    
df_current = pd.DataFrame(columns=['strain','length','flag','position','threshold'])
df_10000 = pd.DataFrame(columns=['tool','strain','length','flag','position','threshold'])

for s in strain:
    for t in tools:
        file='../Data/raw_data/mouse/custom_vcf_fulldata/'+str(th)+'t/deletions/nf_'+str(th)+'t.'+t+'.'+s+'.chr19.100p_sorted.modified.vcf'
        
        if os.path.exists(file):
            callset = allel.read_vcf(file,fields='*')
            if callset!=None:
                df_current = pd.DataFrame({'tool': t, 'strain': s, 'length': callset['variants/SVLEN'],'flag': callset['variants/FLAG'],'position': callset['variants/POS'],'threshold': th})
                df_10000 = pd.concat([df_current, df_10000],ignore_index=True)
            
            else:
                print("Empty File: " + file)
                
        else:
            print("Nonexistant File: " + file)
        
df_10000.head()

/home/vs/.local/lib/python3.5/site-packages/ipykernel_launcher.py:16: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  app.launch_new_instance()

  flag length position strain threshold             tool
0   FP    228  3235828   LP_J     10000  manta_diploidSV
1   FP    288  3236916   LP_J     10000  manta_diploidSV
2   FP   1728  6055200   LP_J     10000  manta_diploidSV
3   FP    579  6057079   LP_J     10000  manta_diploidSV
4   FP   1914  7215483   LP_J     10000  manta_diploidSV

In [24]:
#10000 threshold non-deletions

th=10000    
df_current = pd.DataFrame(columns=['strain','length','flag','position','threshold'])
df_10000_nondel = pd.DataFrame(columns=['tool','strain','length','flag','position','threshold'])

for s in strain:
    for t in tools:
        file='../Data/raw_data/mouse/custom_vcf_fulldata/'+str(th)+'t/non-deletions/nf_'+str(th)+'t.'+t+'.'+s+'.chr19.100p_sorted.modified.nondel.vcf'
        
        
        callset = allel.read_vcf(file,fields='*')
        if callset!=None:
            df_current = pd.DataFrame({'tool': t, 'strain': s, 'length': callset['variants/SVLEN'],'flag': callset['variants/FLAG'],'position': callset['variants/POS'],'threshold': th})
            df_10000_nondel = pd.concat([df_current, df_10000_nondel],ignore_index=True)
        else:
            print("Empty File: " + file)
           
        
df_10000_nondel.head()

/home/vs/.local/lib/python3.5/site-packages/ipykernel_launcher.py:15: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  from ipykernel import kernelapp as app

  flag length position strain threshold             tool
0          -1        0   LP_J     10000  manta_diploidSV
1          -1        0   LP_J     10000  manta_diploidSV
2   TN     93  6054981   LP_J     10000  manta_diploidSV
3   TN   1728  6055200   LP_J     10000  manta_diploidSV
4   TN    579  6057079   LP_J     10000  manta_diploidSV

In [25]:
%store df_10
%store df_100
%store df_1000
%store df_10000
%store df_10_nondel
%store df_100_nondel
%store df_1000_nondel
%store df_10000_nondel

Stored 'df_10' (DataFrame)
Stored 'df_100' (DataFrame)
Stored 'df_1000' (DataFrame)
Stored 'df_10000' (DataFrame)
Stored 'df_10_nondel' (DataFrame)
Stored 'df_100_nondel' (DataFrame)
Stored 'df_1000_nondel' (DataFrame)
Stored 'df_10000_nondel' (DataFrame)

In [26]:
df_10.to_csv('../Data/analysis_files/df_10.csv')
df_100.to_csv('../Data/analysis_files/df_100.csv')
df_1000.to_csv('../Data/analysis_files/df_1000.csv')
df_10000.to_csv('../Data/analysis_files/df_10000.csv')

df_10_nondel.to_csv('../Data/analysis_files/df_10_nondel.csv')
df_100_nondel.to_csv('../Data/analysis_files/df_100_nondel.csv')
df_1000_nondel.to_csv('../Data/analysis_files/df_1000_nondel.csv')
df_10000_nondel.to_csv('../Data/analysis_files/df_10000_nondel.csv')

## Concatenate

In [27]:
#List of your dataframes
#removed df_0 and df_0_nondel for graphing purposes
pdList = [df_10,df_100,df_1000,df_10000,df_10_nondel,df_100_nondel,df_1000_nondel,df_10000_nondel] 
df_cat = pd.concat(pdList)

In [28]:
df_cat.head()

  flag length position strain threshold             tool
0   FP    228  3235828   LP_J        10  manta_diploidSV
1   FP    288  3236916   LP_J        10  manta_diploidSV
2   FP     93  6054981   LP_J        10  manta_diploidSV
3   FP   1728  6055200   LP_J        10  manta_diploidSV
4   FP    579  6057079   LP_J        10  manta_diploidSV

In [29]:
#output counts for TP, FP, TN rows are not the same as Varuni's; due to missing files?
group_data_TP=df_cat[df_cat['flag'] == 'TP'].groupby(['tool','threshold','strain'],as_index=False)['flag'].count()
group_data_TP=group_data_TP.rename(columns={"flag": "nTP"})
group_data_TP.shape

(462, 4)

In [30]:
group_data_TP.head(20)

         tool  threshold   strain  nTP
0   BioGraph*         10    AKR_J   36
1   BioGraph*         10      A_J   47
2   BioGraph*         10  BALB_CJ   45
3   BioGraph*         10  C3H_HeJ   41
4   BioGraph*         10    CBA_J   44
5   BioGraph*         10   DBA_2J   45
6   BioGraph*         10     LP_J   39
7   BioGraph*        100    AKR_J  249
8   BioGraph*        100      A_J  279
9   BioGraph*        100  BALB_CJ  269
10  BioGraph*        100  C3H_HeJ  251
11  BioGraph*        100    CBA_J  272
12  BioGraph*        100   DBA_2J  285
13  BioGraph*        100     LP_J  222
14  BioGraph*       1000    AKR_J  269
15  BioGraph*       1000      A_J  304
16  BioGraph*       1000  BALB_CJ  294
17  BioGraph*       1000  C3H_HeJ  278
18  BioGraph*       1000    CBA_J  302
19  BioGraph*       1000   DBA_2J  316

In [31]:
group_data_FP=df_cat[df_cat['flag'] == 'FP'].groupby(['tool','threshold','strain'],as_index=False)['flag'].count()
group_data_FP=group_data_FP.rename(columns={"flag": "nFP"})
group_data_FP.shape

(476, 4)

In [32]:
group_data_FP.head()

        tool  threshold   strain  nFP
0  BioGraph*         10    AKR_J  389
1  BioGraph*         10      A_J  421
2  BioGraph*         10  BALB_CJ  417
3  BioGraph*         10  C3H_HeJ  416
4  BioGraph*         10    CBA_J  445

In [33]:
group_data_TN=df_cat[df_cat['flag'] == 'TN'].groupby(['tool','threshold','strain'],as_index=False)['flag'].count()
group_data_TN=group_data_TN.rename(columns={"flag": "nTN"})
group_data_TN.shape

(476, 4)

In [34]:
#fill missing combinations with 0s
#removed 0 threshold group since it = 0 for all tools
for s in strain:
    for t in tools:
        for th in [10,100,1000,10000]:
            if not (((group_data_TP['tool'] == t) & (group_data_TP['strain'] == s) & (group_data_TP['threshold'] == th)).any()):
                group_data_TP = group_data_TP.append({'tool' : t , 'strain' : s,'threshold' : th,'nTP' : 0} , ignore_index=True)
group_data_TP.shape

(476, 4)

In [35]:
for s in strain:
    for t in tools:
        for th in [10,100,1000,10000]:
            if not (((group_data_FP['tool'] == t) & (group_data_FP['strain'] == s) & (group_data_FP['threshold'] == th)).any()):
                #group_data_FP = group_data_FP.append({'tool' : t , 'strain' : s,'threshold' : th,'nFP' : 0} , ignore_index=True)
                print (s,t,th)
group_data_FP.shape

(476, 4)

In [36]:
for s in strain:
    for t in tools:
        for th in [10,100,1000,10000]:
            if not (((group_data_TN['tool'] == t) & (group_data_TN['strain'] == s) & (group_data_TN['threshold'] == th)).any()):
                group_data_TN = group_data_TN.append({'tool' : t , 'strain' : s,'threshold' : th,'nTN' : 0} , ignore_index=True)
                #print (s,t,th)
group_data_TN.shape

(476, 4)

In [37]:
#merge TP and FP
df_merge=pd.merge(group_data_TP, group_data_FP,on=['tool','threshold','strain'])
df_merge=pd.merge(df_merge, group_data_TN,on=['tool','threshold','strain'])
df_merge.shape

(476, 6)

In [38]:
df_merge.head(10)

        tool  threshold   strain  nTP  nFP  nTN
0  BioGraph*         10    AKR_J   36  389  206
1  BioGraph*         10      A_J   47  421  220
2  BioGraph*         10  BALB_CJ   45  417  237
3  BioGraph*         10  C3H_HeJ   41  416  247
4  BioGraph*         10    CBA_J   44  445  270
5  BioGraph*         10   DBA_2J   45  454  279
6  BioGraph*         10     LP_J   39  336  213
7  BioGraph*        100    AKR_J  249  176  289
8  BioGraph*        100      A_J  279  189  317
9  BioGraph*        100  BALB_CJ  269  193  330

In [39]:
#true SV deletions
df_current = pd.DataFrame(columns=['strain','length'])
df = pd.DataFrame(columns=['strain','length'])


for s in strain:
    file='../Data/gold_standard/mouse_vcf/'+s+'_reference.vcf'
    callset = allel.read_vcf(file,fields='*')
    
    df_current = pd.DataFrame({'strain': s, 'length': callset['variants/SVLEN']})
    df = pd.concat([df_current, df],ignore_index=True)
group_data_true = df.groupby(['strain'],as_index=False).count()
group_data_true=group_data_true.rename(columns={"length": "n_true"})
group_data_true

/home/vs/.local/lib/python3.5/site-packages/ipykernel_launcher.py:11: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  # This is added back by InteractiveShellApp.init_path()

    strain  n_true
0    AKR_J     504
1      A_J     533
2  BALB_CJ     545
3  C3H_HeJ     539
4    CBA_J     586
5   DBA_2J     609
6     LP_J     483

In [40]:
df_merge=pd.merge(df_merge, group_data_true)
df_merge.shape

(476, 7)

In [41]:
df_merge

                tool  threshold strain  nTP    nFP   nTN  n_true
0          BioGraph*         10  AKR_J   36    389   206     504
1          BioGraph*        100  AKR_J  249    176   289     504
2          BioGraph*       1000  AKR_J  269    156   299     504
3          BioGraph*      10000  AKR_J  291    134   347     504
4        breakdancer         10  AKR_J    9    527   253     504
5        breakdancer        100  AKR_J  254    282   314     504
6        breakdancer       1000  AKR_J  311    225   348     504
7        breakdancer      10000  AKR_J  325    211   393     504
8             clever         10  AKR_J   54   9551    31     504
9             clever        100  AKR_J  336   9269    53     504
10            clever       1000  AKR_J  396   9209   188     504
11            clever      10000  AKR_J  488   9117   298     504
12             crest        100  AKR_J   67    159  1007     504
13             crest       1000  AKR_J  138     88  1015     504
14             crest      10000  AKR_J  149     77  1099     504
15             delly         10  AKR_J   69    854   117     504
16             delly        100  AKR_J  311    612   188     504
17             delly       1000  AKR_J  353    570   208     504
18             delly      10000  AKR_J  405    518   379     504
19              gasv        100  AKR_J   68  12328     9     504
20              gasv       1000  AKR_J  304  12092    35     504
21              gasv      10000  AKR_J  496  11900   508     504
22       genomestrip         10  AKR_J   12    218   116     504
23       genomestrip        100  AKR_J  126    104   170     504
24       genomestrip       1000  AKR_J  148     82   188     504
25       genomestrip      10000  AKR_J  156     74   298     504
26            gridss         10  AKR_J   58   2376    46     504
27            gridss        100  AKR_J  317   2117    84     504
28            gridss       1000  AKR_J  384   2050   123     504
29            gridss      10000  AKR_J  464   1970   500     504
..               ...        ...    ...  ...    ...   ...     ...
446  manta_diploidSV         10   LP_J   60    422   873     483
447  manta_diploidSV        100   LP_J  312    170  1052     483
448  manta_diploidSV       1000   LP_J  337    145  1077     483
449  manta_diploidSV      10000   LP_J  361    121  1293     483
450         mistrvar         10   LP_J   18   5554    54     483
451         mistrvar        100   LP_J   97   5475    59     483
452         mistrvar       1000   LP_J  183   5389    82     483
453         mistrvar      10000   LP_J  430   5142   789     483
454           pindel         10   LP_J   43  76321    43     483
455           pindel        100   LP_J  195  76169    45     483
456           pindel       1000   LP_J  340  76024   131     483
457           pindel      10000   LP_J  480  75884  4239     483
458           popdel         10   LP_J    6    216   256     483
459           popdel        100   LP_J  173     49   317     483
460           popdel       1000   LP_J  210     12   336     483
461           popdel      10000   LP_J  215      7   359     483
462        rdxplorer         10   LP_J    4   2662    53     483
463        rdxplorer        100   LP_J  132   2534    27     483
464        rdxplorer       1000   LP_J  227   2439    59     483
465        rdxplorer      10000   LP_J  393   2273   187     483
466           smoove         10   LP_J   78    322   245     483
467           smoove        100   LP_J  281    119   331     483
468           smoove       1000   LP_J  315     85   348     483
469           smoove      10000   LP_J  331     69   423     483
470         sniffles         10   LP_J   44    142   352     483
471         sniffles        100   LP_J  121     65   366     483
472         sniffles       1000   LP_J  129     57   369     483
473         sniffles      10000   LP_J  143     43   382     483
474             gasv         10   LP_J    0  11605     9     483
475            crest         10   LP_J    0    299  3517     483

[476 rows x 7 columns]

## Calculating precision, sensitivity, specificity, f-score

In [42]:
df_merge['nFN']=df_merge['n_true']-df_merge['nTP']

df_merge['sensitivity']=df_merge['nTP']/df_merge['n_true']
df_merge['precision']=df_merge['nTP']/(df_merge['nTP']+df_merge['nFP'])
df_merge['specificity']=df_merge['nTN']/(df_merge['nTN']+df_merge['nFP'])
df_merge['f-score']=2*(df_merge['sensitivity']*df_merge['precision'])/(df_merge['sensitivity']+df_merge['precision']+0.00000001)
df_merge.head()

,tool,threshold,strain,nTP,nFP,nTN,n_true,nFN,sensitivity,precision,specificity,f-score
0,BioGraph*,10,AKR_J,36,389,206,504,468,0.071429,0.084706,0.346218,0.077503
1,BioGraph*,100,AKR_J,249,176,289,504,255,0.494048,0.585882,0.621505,0.536060
2,BioGraph*,1000,AKR_J,269,156,299,504,235,0.533730,0.632941,0.657143,0.579117
3,BioGraph*,10000,AKR_J,291,134,347,504,213,0.577381,0.684706,0.721414,0.626480
4,breakdancer,10,AKR_J,9,527,253,504,495,0.017857,0.016791,0.324359,0.017308

In [43]:
#count number of TP/FP/TN/FN for each tool at each threshold
df_sum=df_merge.groupby(['tool','threshold'],as_index=False)['nTP','nFP','nFN','nTN'].sum()
df_sum.head(10)

          tool  threshold   nTP    nFP   nFN   nTN
0    BioGraph*         10   297   2878  3502  1672
1    BioGraph*        100  1827   1348  1972  2249
2    BioGraph*       1000  2004   1171  1795  2331
3    BioGraph*      10000  2163   1012  1636  2717
4  breakdancer         10    58   3484  3741  2026
5  breakdancer        100  1883   1659  1916  2483
6  breakdancer       1000  2420   1122  1379  2813
7  breakdancer      10000  2522   1020  1277  3247
8       clever         10   486  13270  3313  1086
9       clever        100  2613  11143  1186  1963

In [44]:
%store df_sum

Stored 'df_sum' (DataFrame)

In [45]:
df_sum.to_csv('../Data/analysis_files/df_sum.csv')

In [46]:
df_merge.to_csv('../Data/analysis_files/df_merged.csv')

In [47]:
df_merge.head()

,tool,threshold,strain,nTP,nFP,nTN,n_true,nFN,sensitivity,precision,specificity,f-score
0,BioGraph*,10,AKR_J,36,389,206,504,468,0.071429,0.084706,0.346218,0.077503
1,BioGraph*,100,AKR_J,249,176,289,504,255,0.494048,0.585882,0.621505,0.536060
2,BioGraph*,1000,AKR_J,269,156,299,504,235,0.533730,0.632941,0.657143,0.579117
3,BioGraph*,10000,AKR_J,291,134,347,504,213,0.577381,0.684706,0.721414,0.626480
4,breakdancer,10,AKR_J,9,527,253,504,495,0.017857,0.016791,0.324359,0.017308